# Generated by Django 4.1 on 2026-07-21 12:49

import dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('acronym', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['acronym'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('outcome', models.CharField(choices=[('Outcome 1', 'Outcome 1: Sustainable Growth'), ('Outcome 2', 'Outcome 2: Human Capital'), ('Outcome 3', 'Outcome 3: Resilience')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('knowledge_type', models.CharField(choices=[('Evidence', 'Evidence'), ('Insights', 'Insights'), ('Experience', 'Experience'), ('Resources', 'Resources')], default='Evidence', max_length=20)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Archived', 'Archived'), ('Active', 'Active')], default='Draft', max_length=20)),
                ('content_text', models.TextField(blank=True, help_text='Extracted text from uploaded files.')),
                ('is_indexed', models.BooleanField(default=False)),
                ('embedding_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_items', to='dashboard.agency')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.category')),
                ('keywords', models.ManyToManyField(blank=True, to='dashboard.keyword')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SDG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('uploaded_file', models.FileField(upload_to='knowledge_versions/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('knowledge_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='dashboard.knowledgeitem')),
            ],
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.region'),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='sdgs',
            field=models.ManyToManyField(blank=True, to='dashboard.sdg'),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.theme'),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='KnowledgeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=dashboard.models.knowledge_file_upload_path)),
                ('file_type', models.CharField(choices=[('PDF', 'PDF'), ('DOCX', 'Word Document'), ('XLSX', 'Excel Spreadsheet'), ('PPTX', 'PowerPoint'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('MAP', 'Map'), ('OTHER', 'Other')], default='PDF', max_length=20)),
                ('extracted_text', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('knowledge_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='dashboard.knowledgeitem')),
            ],
        ),
    ]
